environment:
  name: bgfast
  project: bgfast
  validation-type: dev
  selected:
  ### ===========================================
  ### CORE FOUNDATION MODULES (Deploy First)
  ### ===========================================
  #- modules/common/foundation                ### Ingestion of raw data + basic access management

  ### ===========================================
  ### NEAT BASIC DATA MODEL & APPS
  ### ===========================================
  - modules/neat-basic                       ### NEAT Basic data model + Streamlit apps

  ### ===========================================
  ### ADMINISTRATION & MANAGEMENT (Optional)
  ### ===========================================
  #- modules/streamlit-github-deployer       ### GitHub Repo to CDF Deployer

variables:
  # Environment Configuration
  default_location: neat-basic               # Name of the location for NEAT Basic
  source_asset: neat                         # Source of the assets
  source_event: neat                         # Source of the events
  source_workorder: neat                     # Source of the workorders
  source_files: neat                         # Source of the files
  source_timeseries: neat                    # Source of the timeseries
  source_simulated: neat                     # Source for simulated data
  
  # NEAT Basic Data Model Configuration
  neat_basic_space: neat-basic               # Name of the NEAT Basic space
  neat_basic_container: BasicAsset           # Name of the BasicAsset container
  neat_basic_view: BasicAsset                # Name of the BasicAsset view
  neat_basic_dataset: neat-basic-dataset     # Name of the NEAT Basic dataset
  
  # Data Model Configuration
  company_process_industries_extensions: neat_basic_data  # Name of the space for NEAT Basic data model
  company_process_industries_extensions_external_id: NeatBasic # Name of the NEAT Basic data model
  company_process_industries_extensions_external_id_destination: NeatBasic  # NEAT Basic extension
  
  # Authentication Configuration
  superuser_sourceid: ${SUPERUSER_SOURCEID_ENV} # Source id for the super users in auth
  my_user_identifier: ${USER_IDENTIFIER}     # User identifier for custom_access_management
  readwrite_source_id: ${SUPERUSER_SOURCEID_ENV}

  # CDF Configuration (populated from .env file)
  CDF_PROJECT: ${CDF_PROJECT}
  CDF_CLUSTER: ${CDF_CLUSTER}
  CDF_URL: https://${CDF_CLUSTER}.cognitedata.com
  
  # IDP Configuration
  IDP_CLIENT_ID: ${IDP_CLIENT_ID}
  IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
  IDP_SCOPES: ${IDP_SCOPES}
  IDP_TENANT_ID: ${IDP_TENANT_ID}
  IDP_TOKEN_URL: ${IDP_TOKEN_URL}
  
  # Function Configuration (if needed for NEAT Basic functions)
  function_clientId: ${FUNCTION_CLIENT_ID}
  function_clientSecret: ${FUNCTION_CLIENT_SECRET}
  transformation_clientId: ${TRANSFORMATION_CLIENT_ID}
  transformation_clientSecret: ${TRANSFORMATION_CLIENT_SECRET}
  
  # NEAT Basic Testing Configuration
  neat_test_asset_prefix: test_neat_          # Prefix for test assets
  neat_sample_asset_count: 10                # Default number of sample assets to create
  neat_cleanup_enabled: true                 # Enable cleanup of test data
