environment:
  name: bgfast
  project: bgfast
  validation-type: dev
  selected:
  ### ===========================================
  ### CORE FOUNDATION MODULES (Deploy First)
  ### ===========================================
  #- modules/common/foundation                ### Ingestion of raw data + basic access management

  ### ===========================================
  ### HELLO WORLD NEAT DATA MODEL & APPS
  ### ===========================================
  - modules/hw-neat                          ### Hello World NEAT data model + Streamlit apps

  ### ===========================================
  ### ADMINISTRATION & MANAGEMENT (Optional)
  ### ===========================================
  #- modules/streamlit-github-deployer       ### GitHub Repo to CDF Deployer

variables:
  # Environment Configuration
  default_location: hw-neat                  # Name of the location for Hello World NEAT
  source_asset: hw-neat                      # Source of the assets
  source_event: hw-neat                      # Source of the events
  source_workorder: hw-neat                  # Source of the workorders
  source_files: hw-neat                      # Source of the files
  source_timeseries: hw-neat                 # Source of the timeseries
  source_simulated: hw-neat                  # Source for simulated data
  
  # Hello World NEAT Data Model Configuration
  hw_neat_space: hw-neat                     # Name of the HW NEAT space
  hw_neat_container: HWNeatBasic             # Name of the HWNeatBasic container
  hw_neat_view: HWNeatBasic                  # Name of the HWNeatBasic view
  hw_neat_dataset: hw-neat-dataset           # Name of the HW NEAT dataset
  
  # Data Model Configuration
  company_process_industries_extensions: hw_neat_data  # Name of the space for HW NEAT data model
  company_process_industries_extensions_external_id: HWNeat # Name of the HW NEAT data model
  company_process_industries_extensions_external_id_destination: HWNeat  # HW NEAT extension
  
  # Authentication Configuration
  superuser_sourceid: ${SUPERUSER_SOURCEID_ENV} # Source id for the super users in auth
  my_user_identifier: ${USER_IDENTIFIER}     # User identifier for custom_access_management
  readwrite_source_id: ${SUPERUSER_SOURCEID_ENV}

  # CDF Configuration (populated from .env file)
  CDF_PROJECT: ${CDF_PROJECT}
  CDF_CLUSTER: ${CDF_CLUSTER}
  CDF_URL: https://${CDF_CLUSTER}.cognitedata.com
  
  # IDP Configuration
  IDP_CLIENT_ID: ${IDP_CLIENT_ID}
  IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
  IDP_SCOPES: ${IDP_SCOPES}
  IDP_TENANT_ID: ${IDP_TENANT_ID}
  IDP_TOKEN_URL: ${IDP_TOKEN_URL}
  
  # Function Configuration (if needed for HW NEAT functions)
  function_clientId: ${FUNCTION_CLIENT_ID}
  function_clientSecret: ${FUNCTION_CLIENT_SECRET}
  transformation_clientId: ${TRANSFORMATION_CLIENT_ID}
  transformation_clientSecret: ${TRANSFORMATION_CLIENT_SECRET}
  
  # Hello World NEAT Testing Configuration
  hw_neat_test_asset_prefix: hw_test_        # Prefix for test assets
  hw_neat_sample_asset_count: 10             # Default number of sample assets to create
  hw_neat_cleanup_enabled: true              # Enable cleanup of test data
